#if !defined(AFX_QCLICK_H__DDC8924D_263F_489F_81B8_F5A4D1D3A77B__INCLUDED_)
#define AFX_QCLICK_H__DDC8924D_263F_489F_81B8_F5A4D1D3A77B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CQClick wrapper class

class CQClick : public CWnd
{
protected:
	DECLARE_DYNCREATE(CQClick)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8a4af128, 0x436e, 0x4705, { 0xbf, 0x9a, 0x7a, 0xb8, 0x86, 0x19, 0xfc, 0x24 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL InitHost();
	CString GetHostInfo(long lFlag);
	long SetHostChannel(short nChannelNo);
	long StartSession(LPCTSTR pClassName, LPCTSTR pTeacherName, long lMaxStudents, short nSessionType, BOOL bLoginFlag, BOOL bAutoLoginFlag);
	long StartQuestion(short nQuestionNo, short nQuestionType, short nNumberOfOption, BOOL bIsSendQuestion, LPCTSTR pQuestionInfo, LPCTSTR pCorrectAnswer, short nQuestionSessionType, short nReanswerTimes);
	long StopQuestion();
	long StopSession();
	BOOL AllowLogin(long lSerialNO, LPCTSTR pStudentID, BOOL bIsAllowLogin, BOOL bIsSendStudentName, LPCTSTR pStudentName);
	BOOL CloseHost();
	long SetKeypadNO(long lKeypadNO);
	long HomeworkSetExamTitle(short nExamID, LPCTSTR pExamTitle, short nQuestionNum, BOOL bRandomPaper);
	long HomeworkSetQuestionInfo(short nQuestionNo, short nQuestionType, LPCTSTR pQuestionInfo, LPCTSTR pAnswer);
	CString GetStudentAnswer(LPCTSTR pStudentID, short nQuestionNo);
	long HomeworkSendExamInfo();
	long StartSessionRF500(LPCTSTR pClassName, LPCTSTR pTeacherName, long lMaxStudents, short nSessionType, BOOL bLoginFlag, BOOL bAutoLoginFlag, short nReanswerTimes);
	long StartTestKeypad();
	long StopTestKeypad();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_QCLICK_H__DDC8924D_263F_489F_81B8_F5A4D1D3A77B__INCLUDED_)
